package domain

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestNewContainer(t *testing.T) {
	container := NewContainer("test-container-1", "parent-container", BasicContainer)

	assert.NotNil(t, container)
	assert.Equal(t, "test-container-1", container.ID())
	assert.Equal(t, "parent-container", container.ParentID)
	assert.Equal(t, BasicContainer, container.ContainerType)
	// Members property has been removed - membership is now managed via repository

	// Check that events were emitted (both resource created and container created)
	events := container.UncommittedEvents()
	assert.Len(t, events, 2)
	assert.Equal(t, EventTypeResourceCreated, events[0].(*EntityEvent).Type)
	assert.Equal(t, EventTypeContainerCreated, events[1].(*EntityEvent).Type)
}

func TestNewContainer_AutoGeneratedID(t *testing.T) {
	container := NewContainer("", "parent-container", BasicContainer)

	assert.NotNil(t, container)
	assert.NotEmpty(t, container.ID())
	assert.Equal(t, "parent-container", container.ParentID)
	assert.Equal(t, BasicContainer, container.ContainerType)
}

func TestNewContainer_RootContainer(t *testing.T) {
	container := NewContainer("root", "", BasicContainer)

	assert.NotNil(t, container)
	assert.Equal(t, "root", container.ID())
	assert.Empty(t, container.ParentID)
	assert.Equal(t, BasicContainer, container.ContainerType)
}

func TestContainer_AddMember(t *testing.T) {
	container := NewContainer("test-container", "", BasicContainer)
	initialEvents := len(container.UncommittedEvents())

	// Create a resource to add
	resource := NewResource("resource-1", "text/plain", []byte("test data"))

	err := container.AddMember(resource)
	assert.NoError(t, err)

	// Check that a member added event was emitted
	events := container.UncommittedEvents()
	assert.Len(t, events, initialEvents+1)
	assert.Equal(t, EventTypeMemberAdded, events[len(events)-1].(*EntityEvent).Type)
}

func TestContainer_AddMember_NilResource(t *testing.T) {
	container := NewContainer("test-container", "", BasicContainer)

	// Try to add a nil resource
	err := container.AddMember(nil)
	assert.Error(t, err)
	assert.Contains(t, err.Error(), "resource cannot be nil")
}

func TestContainer_RemoveMember(t *testing.T) {
	container := NewContainer("test-container", "", BasicContainer)
	initialEvents := len(container.UncommittedEvents())

	err := container.RemoveMember("resource-1")
	assert.NoError(t, err)

	// Check that a member removed event was emitted
	events := container.UncommittedEvents()
	assert.Len(t, events, initialEvents+1)
	assert.Equal(t, EventTypeMemberRemoved, events[len(events)-1].(*EntityEvent).Type)
}

func TestContainer_RemoveMember_EmptyID(t *testing.T) {
	container := NewContainer("test-container", "", BasicContainer)

	err := container.RemoveMember("")
	assert.Error(t, err)
	assert.Contains(t, err.Error(), "resource ID cannot be empty")
}

func TestContainer_HasMember(t *testing.T) {
	container := NewContainer("test-container", "", BasicContainer)

	// HasMember now returns false as it needs repository access
	assert.False(t, container.HasMember("resource-1"))
	assert.False(t, container.HasMember("resource-2"))
}

func TestContainer_GetMemberCount(t *testing.T) {
	container := NewContainer("test-container", "", BasicContainer)

	// GetMemberCount now returns 0 as it needs repository access
	assert.Equal(t, 0, container.GetMemberCount())
}

func TestContainer_IsEmpty(t *testing.T) {
	container := NewContainer("test-container", "", BasicContainer)

	// IsEmpty now returns true as it needs repository access
	assert.True(t, container.IsEmpty())
}

func TestContainer_ValidateHierarchy_CircularReference(t *testing.T) {
	container := NewContainer("container-1", "container-2", BasicContainer)

	err := container.ValidateHierarchy([]string{"container-2", "container-3", "container-1"})
	assert.Error(t, err)
	assert.Contains(t, err.Error(), "circular reference detected")
}

func TestContainer_ValidateHierarchy_Valid(t *testing.T) {
	container := NewContainer("container-1", "container-2", BasicContainer)

	err := container.ValidateHierarchy([]string{"container-2", "container-3", "root"})
	assert.NoError(t, err)
}

func TestContainer_ValidateHierarchy_SelfReference(t *testing.T) {
	container := NewContainer("container-1", "container-1", BasicContainer)

	err := container.ValidateHierarchy([]string{})
	assert.Error(t, err)
	assert.Contains(t, err.Error(), "container cannot be its own parent")
}

func TestContainer_SetTitle(t *testing.T) {
	container := NewContainer("test-container", "", BasicContainer)

	container.SetTitle("My Container")
	assert.Equal(t, "My Container", container.GetTitle())
	assert.Equal(t, "My Container", container.GetMetadata()["title"])
}

func TestContainer_SetDescription(t *testing.T) {
	container := NewContainer("test-container", "", BasicContainer)

	container.SetDescription("Container description")
	assert.Equal(t, "Container description", container.GetDescription())
	assert.Equal(t, "Container description", container.GetMetadata()["description"])
}

func TestContainer_GetPath(t *testing.T) {
	container := NewContainer("test-container", "parent-container", BasicContainer)

	path := container.GetPath()
	assert.Equal(t, "parent-container/test-container", path)
}

func TestContainer_GetPath_Root(t *testing.T) {
	container := NewContainer("root", "", BasicContainer)

	path := container.GetPath()
	assert.Equal(t, "root", path)
}

func TestContainer_Update(t *testing.T) {
	container := NewContainer("test-container", "", BasicContainer)
	initialEvents := len(container.UncommittedEvents())

	container.SetTitle("Updated Title")
	container.SetDescription("Updated Description")

	// Check that update events were emitted (one for each SetTitle and SetDescription)
	events := container.UncommittedEvents()
	assert.Len(t, events, initialEvents+2)
	assert.Equal(t, EventTypeContainerUpdated, events[len(events)-2].(*EntityEvent).Type)
	assert.Equal(t, EventTypeContainerUpdated, events[len(events)-1].(*EntityEvent).Type)
}

func TestContainer_Delete(t *testing.T) {
	container := NewContainer("test-container", "", BasicContainer)
	initialEvents := len(container.UncommittedEvents())

	container.Delete()

	// Check that a delete event was emitted
	events := container.UncommittedEvents()
	assert.Len(t, events, initialEvents+1)
	assert.Equal(t, EventTypeContainerDeleted, events[len(events)-1].(*EntityEvent).Type)
}

func TestContainer_Delete_Success(t *testing.T) {
	container := NewContainer("test-container", "", BasicContainer)
	initialEvents := len(container.UncommittedEvents())

	// Delete now succeeds since empty check is done at service layer
	err := container.Delete()
	assert.NoError(t, err)

	// Check that a delete event was emitted
	events := container.UncommittedEvents()
	assert.Len(t, events, initialEvents+1)
	assert.Equal(t, EventTypeContainerDeleted, events[len(events)-1].(*EntityEvent).Type)
}

func TestContainerType_String(t *testing.T) {
	assert.Equal(t, "BasicContainer", BasicContainer.String())
	assert.Equal(t, "DirectContainer", DirectContainer.String())
}

func TestContainerType_IsValid(t *testing.T) {
	assert.True(t, BasicContainer.IsValid())
	assert.True(t, DirectContainer.IsValid())
	assert.False(t, ContainerType("InvalidType").IsValid())
}
