package domain

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestNewResource(t *testing.T) {
	ctx := context.Background()
	resource := NewResource(ctx, "test-resource-1", "text/turtle", []byte("@prefix ex: <http://example.org/> ."))

	assert.NotNil(t, resource)
	assert.Equal(t, "test-resource-1", resource.ID())
	assert.Equal(t, "text/turtle", resource.GetContentType())
	assert.Equal(t, []byte("@prefix ex: <http://example.org/> ."), resource.GetData())
	assert.NotNil(t, resource.GetMetadata())

	// Check that an enhanced created event was emitted for RDF format
	events := resource.UncommittedEvents()
	assert.Len(t, events, 1)
	assert.Equal(t, EventTypeResourceCreatedWithRelations, events[0].(*EntityEvent).Type)
}

func TestNewResource_AutoGeneratedID(t *testing.T) {
	ctx := context.Background()
	resource := NewResource(ctx, "", "application/ld+json", []byte(`{"@context": "http://example.org"}`))

	assert.NotNil(t, resource)
	assert.NotEmpty(t, resource.ID())
	assert.Equal(t, "application/ld+json", resource.GetContentType())
	assert.Equal(t, []byte(`{"@context": "http://example.org"}`), resource.GetData())

	// Check that an enhanced created event was emitted for RDF format
	events := resource.UncommittedEvents()
	assert.Len(t, events, 1)
	assert.Equal(t, EventTypeResourceCreatedWithRelations, events[0].(*EntityEvent).Type)
}

func TestResource_FromJSONLD_Valid(t *testing.T) {
	ctx := context.Background()
	resource := NewResource(ctx, "test-id", "text/plain", []byte("initial"))
	initialEvents := len(resource.UncommittedEvents())

	data := []byte(`{
		"@context": "http://schema.org",
		"@type": "Person",
		"name": "John Doe"
	}`)

	result := resource.FromJSONLD(ctx, data)

	assert.Equal(t, resource, result)
	assert.True(t, resource.IsValid())
	assert.Equal(t, "application/ld+json", resource.GetContentType())
	assert.Equal(t, data, resource.GetData())
	assert.Equal(t, "application/ld+json", resource.GetMetadata()["originalFormat"])
	assert.NotNil(t, resource.GetMetadata()["updatedAt"])

	// Check that an enhanced update event was emitted for JSON-LD (RDF format)
	events := resource.UncommittedEvents()
	assert.Len(t, events, initialEvents+1)
	assert.Equal(t, EventTypeResourceUpdated, events[len(events)-1].(*EntityEvent).Type)
}

func TestResource_FromJSONLD_Invalid(t *testing.T) {
	ctx := context.Background()
	resource := NewResource(ctx, "test-id", "text/plain", []byte("initial"))

	// Test invalid JSON
	result := resource.FromJSONLD(ctx, []byte(`{"invalid": json}`))
	assert.Equal(t, resource, result)
	assert.False(t, resource.IsValid())
	errors := resource.Errors()
	assert.Len(t, errors, 1)
	assert.Contains(t, errors[0].Error(), "invalid JSON-LD format")

	// Reset errors for next test
	resource.Reset()

	// Test JSON without @context
	result = resource.FromJSONLD(ctx, []byte(`{"@type": "Person", "name": "John Doe"}`))
	assert.Equal(t, resource, result)
	assert.False(t, resource.IsValid())
	errors = resource.Errors()
	assert.Len(t, errors, 1)
	assert.Contains(t, errors[0].Error(), "JSON-LD data must contain @context")
}

func TestResource_FromRDF_Valid(t *testing.T) {
	ctx := context.Background()
	resource := NewResource(ctx, "test-id", "text/plain", []byte("initial"))
	initialEvents := len(resource.UncommittedEvents())

	data := []byte(`<rdf:RDF><person>John</person></rdf:RDF>`)

	result := resource.FromRDF(ctx, data)

	assert.Equal(t, resource, result)
	assert.True(t, resource.IsValid())
	assert.Equal(t, "application/rdf+xml", resource.GetContentType())
	assert.Equal(t, data, resource.GetData())
	assert.Equal(t, "application/rdf+xml", resource.GetMetadata()["originalFormat"])
	assert.NotNil(t, resource.GetMetadata()["updatedAt"])

	// Check that an enhanced update event was emitted for RDF/XML format
	events := resource.UncommittedEvents()
	assert.Len(t, events, initialEvents+1)
	assert.Equal(t, EventTypeResourceUpdated, events[len(events)-1].(*EntityEvent).Type)
}

func TestResource_FromRDF_Empty(t *testing.T) {
	ctx := context.Background()
	resource := NewResource(ctx, "test-id", "text/plain", []byte("initial"))

	result := resource.FromRDF(ctx, []byte(``))
	assert.Equal(t, resource, result)
	assert.False(t, resource.IsValid())
	errors := resource.Errors()
	assert.Len(t, errors, 1)
	assert.Contains(t, errors[0].Error(), "RDF/XML data cannot be empty")
}

func TestResource_FromTurtle_Valid(t *testing.T) {
	ctx := context.Background()
	resource := NewResource(ctx, "test-id", "text/plain", []byte("initial"))
	initialEvents := len(resource.UncommittedEvents())

	data := []byte(`@prefix ex: <http://example.org/> .
		ex:person ex:name "John Doe" .`)

	result := resource.FromTurtle(ctx, data)

	assert.Equal(t, resource, result)
	assert.True(t, resource.IsValid())
	assert.Equal(t, "text/turtle", resource.GetContentType())
	assert.Equal(t, data, resource.GetData())
	assert.Equal(t, "text/turtle", resource.GetMetadata()["originalFormat"])
	assert.NotNil(t, resource.GetMetadata()["updatedAt"])

	// Check that an enhanced update event was emitted for Turtle (RDF format)
	events := resource.UncommittedEvents()
	assert.Len(t, events, initialEvents+1)
	assert.Equal(t, EventTypeResourceUpdatedWithRelations, events[len(events)-1].(*EntityEvent).Type)
}

func TestResource_FromTurtle_Empty(t *testing.T) {
	ctx := context.Background()
	resource := NewResource(ctx, "test-id", "text/plain", []byte("initial"))

	result := resource.FromTurtle(ctx, []byte(``))
	assert.Equal(t, resource, result)
	assert.False(t, resource.IsValid())
	errors := resource.Errors()
	assert.Len(t, errors, 1)
	assert.Contains(t, errors[0].Error(), "Turtle data cannot be empty")
}

func TestResource_FromXML_Alias(t *testing.T) {
	ctx := context.Background()
	resource := NewResource(ctx, "test-id", "text/plain", []byte("initial"))
	data := []byte(`<rdf:RDF><person>John</person></rdf:RDF>`)

	result := resource.FromXML(ctx, data)

	assert.Equal(t, resource, result)
	assert.True(t, resource.IsValid())
	assert.Equal(t, "application/rdf+xml", resource.GetContentType())
	assert.Equal(t, data, resource.GetData())
}

func TestResource_ToFormat(t *testing.T) {
	ctx := context.Background()
	// Test same format return
	resource := NewResource(ctx, "test-id", "application/ld+json", []byte(`{"@context": "http://schema.org"}`))

	result, err := resource.ToFormat("application/ld+json")
	assert.NoError(t, err)
	assert.Equal(t, resource.GetData(), result)

	// Test unsupported format
	_, err = resource.ToFormat("application/n-triples")
	assert.Error(t, err)
	assert.Contains(t, err.Error(), "unsupported format")

	// Test format conversion not implemented
	_, err = resource.ToFormat("text/turtle")
	assert.Error(t, err)
	assert.Contains(t, err.Error(), "format conversion from application/ld+json to text/turtle not yet implemented")
}

func TestResource_Update(t *testing.T) {
	ctx := context.Background()
	resource := NewResource(ctx, "test-id", "text/plain", []byte("initial"))
	initialEvents := len(resource.UncommittedEvents())

	newData := []byte("updated content")
	newContentType := "text/turtle"

	resource.Update(ctx, newData, newContentType)

	assert.Equal(t, newData, resource.GetData())
	assert.Equal(t, newContentType, resource.GetContentType())
	assert.NotNil(t, resource.GetMetadata()["updatedAt"])

	// Check that an enhanced update event was emitted for Turtle (RDF format)
	events := resource.UncommittedEvents()
	assert.Len(t, events, initialEvents+1)
	assert.Equal(t, EventTypeResourceUpdatedWithRelations, events[len(events)-1].(*EntityEvent).Type)
}

func TestResource_Delete(t *testing.T) {
	ctx := context.Background()
	resource := NewResource(ctx, "test-id", "text/plain", []byte("content"))
	initialEvents := len(resource.UncommittedEvents())

	resource.Delete(ctx)

	// Check that a delete event was emitted
	events := resource.UncommittedEvents()
	assert.Len(t, events, initialEvents+1)
	assert.Equal(t, EventTypeResourceDeleted, events[len(events)-1].(*EntityEvent).Type)
}

func TestResource_Getters(t *testing.T) {
	ctx := context.Background()
	data := []byte("test content")
	contentType := "text/turtle"
	resource := NewResource(ctx, "test-id", contentType, data)
	resource.SetMetadata("key1", "value1")

	assert.Equal(t, len(data), resource.GetSize())
	assert.Equal(t, contentType, resource.GetContentType())
	assert.Equal(t, data, resource.GetData())

	metadata := resource.GetMetadata()
	assert.Equal(t, "value1", metadata["key1"])
}

func TestResource_ErrorHandling(t *testing.T) {
	ctx := context.Background()
	resource := NewResource(ctx, "test-id", "text/plain", []byte("content"))

	// Test multiple errors accumulation
	resource.FromJSONLD(ctx, []byte(`invalid json`))
	resource.FromRDF(ctx, []byte(``))

	assert.False(t, resource.IsValid())
	errors := resource.Errors()
	assert.Len(t, errors, 2)
	assert.Contains(t, errors[0].Error(), "invalid JSON-LD format")
	assert.Contains(t, errors[1].Error(), "RDF/XML data cannot be empty")

	// Test error reset
	resource.Reset()
	assert.True(t, resource.IsValid())
	assert.Len(t, resource.Errors(), 0)
}

func TestResource_EventIntegration(t *testing.T) {
	ctx := context.Background()
	// Test that all operations properly emit events
	resource := NewResource(ctx, "test-id", "text/plain", []byte("initial"))

	// Should have 1 event (created)
	assert.Len(t, resource.UncommittedEvents(), 1)
	assert.Equal(t, EventTypeResourceCreated, resource.UncommittedEvents()[0].(*EntityEvent).Type)

	// Update via FromJSONLD
	resource.FromJSONLD(ctx, []byte(`{"@context": "http://schema.org"}`))
	assert.True(t, resource.IsValid())

	// Should have 2 events (created + updated with relations)
	assert.Len(t, resource.UncommittedEvents(), 2)
	assert.Equal(t, EventTypeResourceUpdatedWithRelations, resource.UncommittedEvents()[1].(*EntityEvent).Type)

	// Update via Update method
	resource.Update(ctx, []byte("new content"), "text/turtle")

	// Should have 3 events (created + updated + updated with relations)
	assert.Len(t, resource.UncommittedEvents(), 3)
	assert.Equal(t, EventTypeResourceUpdatedWithRelations, resource.UncommittedEvents()[2].(*EntityEvent).Type)

	// Delete
	resource.Delete(ctx)

	// Should have 4 events (created + updated + updated + deleted)
	assert.Len(t, resource.UncommittedEvents(), 4)
	assert.Equal(t, EventTypeResourceDeleted, resource.UncommittedEvents()[3].(*EntityEvent).Type)
}
