# HTTP Server Configuration
http:
  # Server port (default: 8080)
  port: 8080
  
  # Request timeout settings
  read_timeout: 30s
  write_timeout: 30s
  shutdown_timeout: 10s
  
  # Maximum size of request headers in bytes (default: 1MB)
  max_header_bytes: 1048576
  
  # TLS/HTTPS configuration
  tls:
    enabled: false
    cert_file: ""
    key_file: ""

# Logging configuration
log:
  # Log level: debug, info, warn, error (default: info)
  level: info
  
  # Log format: json, text (default: json)
  format: json