# HTTP Server Configuration with TLS
http:
  port: 8443
  read_timeout: 60s
  write_timeout: 60s
  shutdown_timeout: 15s
  max_header_bytes: 2097152  # 2MB
  
  tls:
    enabled: true
    cert_file: "/etc/ssl/certs/server.crt"
    key_file: "/etc/ssl/private/server.key"

log:
  level: debug
  format: json