// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/akeemphilbert/goro/internal/conf"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/go-kratos/kratos/v2/transport/grpc"
	"github.com/go-kratos/kratos/v2/transport/http"
	"github.com/google/wire"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(server *conf.Server, logger log.Logger) (*kratos.App, func(), error) {
	http := server.HTTP
	httpServer := NewHTTPServer(http, logger)
	grpc := server.GRPC
	grpcServer := NewGRPCServer(grpc, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
	}, nil
}

// wire.go:

// ProviderSet is the provider set for Wire dependency injection
var ProviderSet = wire.NewSet(
	NewHTTPServer,
	NewGRPCServer, wire.FieldsOf(new(*conf.Server), "HTTP", "GRPC"),
)

// NewHTTPServer creates a new HTTP server
func NewHTTPServer(c *conf.HTTP, logger log.Logger) *http.Server {
	var opts = []http.ServerOption{http.Network(c.Network), http.Address(c.Addr)}
	if c.Timeout != 0 {
		opts = append(opts, http.Timeout(c.Timeout))
	}

	srv := http.NewServer(opts...)
	return srv
}

// NewGRPCServer creates a new gRPC server
func NewGRPCServer(c *conf.GRPC, logger log.Logger) *grpc.Server {
	var opts = []grpc.ServerOption{grpc.Network(c.Network), grpc.Address(c.Addr)}
	if c.Timeout != 0 {
		opts = append(opts, grpc.Timeout(c.Timeout))
	}

	srv := grpc.NewServer(opts...)
	return srv
}
